### ISSUE TITLE
Gracefully handle Tweets being over 140 characters.

### ISSUE THREAD

**Issue by strugee** [dper/pumptweet#27]
Currently if Twitter rejects a tweet for being over 140 characters, you get the following ugly traceback every time `pt.sh` runs:

```
Traceback (most recent call last):
  File "./pt.py", line 18, in <module>
    pumptweet.pull_and_push()
  File "/home/alex/pumptweet/pumptweet/PumpTweet.py", line 162, in pull_and_push
    self.post_tweets(tweets)
  File "/home/alex/pumptweet/pumptweet/PumpTweet.py", line 137, in post_tweets
    self.twitter_api.PostUpdate(tweet)
  File "/home/alex/pumptweet/local/lib/python2.7/site-packages/twitter/api.py", line 887, in PostUpdate
    data = self._ParseAndCheckTwitter(json.content)
  File "/home/alex/pumptweet/local/lib/python2.7/site-packages/twitter/api.py", line 3530, in _ParseAndCheckTwitter
    self._CheckForTwitterError(data)
  File "/home/alex/pumptweet/local/lib/python2.7/site-packages/twitter/api.py", line 3557, in _CheckForTwitterError
    raise TwitterError(data['errors'])
twitter.error.TwitterError: [{u'message': u'Status is over 140 characters.', u'code': 186}]
```

Now, it'd be nice if this never happened, but as we all know, software has bugs. So: PumpTweet should output an error to the console once (perhaps suggesting that the user file a bug), so that the user gets mail about the error, and then shut up.

**Comment by dper** [comment]
I added some better error handling in https://github.com/dper/pumptweet/commit/0c72d83ef8ab57b7d0d7ece95e458ab4c66ee867.

In general, what is the desired behavior if Twitter rejects a tweet?  Right now, PumpTweet hangs on that single message and won't advance. That makes it easy for us to debug.

On the other hand, a regular user might want to see the error message just once and then move on with life. But that would make debugging hard, so maybe an optional command line parameter is desirable so that when debugging we could say "halt on error".

This also impacts https://github.com/dper/pumptweet/issues/28.

**Comment by dper** [comment]
Errors are now gracefully handled. It's not an ideal solution, but it's better than it was.
