### ISSUE TITLE
Error in ini file on first run

### ISSUE THREAD

**Issue by dper** [dper/pumptweet#36]
In PumpTweet [1.6.1](https://pypi.python.org/pypi/pumptweet/1.6.1), the current version installed using pip, there's a problem with configuration the first time.  Suppose I make an ini file.

```
[pump]
username = something@somesite.url

[twitter]
key = AAAA
secret = BBBB
token = CCCC
token_secret = DDDD

[history]
recent = 
published = 
```

The `recent` and `published` fields are blank because I haven't run the program yet. When I try running the program for the first time, I get a parsing error.

```
Reading the config file...
Traceback (most recent call last):
  File "./bin/pt.py", line 18, in <module>
    pumptweet.pull_and_push()
  File "/home/d/temp/local/lib/python2.7/site-packages/pumptweet/PumpTweet.py", line 155, in pull_and_push
    self.connect_to_servers()
  File "/home/d/temp/local/lib/python2.7/site-packages/pumptweet/PumpTweet.py", line 17, in connect_to_servers
    self.ptp = PumpTweetParser()
  File "/home/d/temp/local/lib/python2.7/site-packages/pumptweet/PumpLogin.py", line 88, in __init__
    self.parse_ini()
  File "/home/d/temp/local/lib/python2.7/site-packages/pumptweet/PumpLogin.py", line 36, in parse_ini
    self._published = parse(date)
  File "/home/d/temp/local/lib/python2.7/site-packages/dateutil/parser.py", line 1164, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "/home/d/temp/local/lib/python2.7/site-packages/dateutil/parser.py", line 558, in parse
    raise ValueError("String does not contain a date.")
ValueError: String does not contain a date.
```

This is bad. The program be OK with empty values.

**Comment by dper** [comment]
A workaround is to put a dummy date for `published`.

```
published = 2016-01-01 00:00:00+00:00
```

**Comment by dper** [comment]
The same bug exists on `master`.

**Comment by dper** [comment]
Fixed in <https://github.com/dper/pumptweet/commit/5370b4780221e284a153a6484f6b2ce5e083dd83>.

Now one can have an ini file with

```
published = 
```

or no `published` line at all, and one will be created appropriately.
