### ISSUE TITLE
socket.timeout: The read operation timed out

### ISSUE THREAD

**Issue by strugee** [dper/pumptweet#39]
I'm getting the following error in cron (but not when running manually, for some reason):

```
Traceback (most recent call last):
  File "/home/alex/pumptweet/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 393, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/alex/pumptweet/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 389, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.4/http/client.py", line 1172, in getresponse
    response.begin()
  File "/usr/lib/python3.4/http/client.py", line 351, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.4/http/client.py", line 313, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.4/socket.py", line 371, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.4/ssl.py", line 745, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.4/ssl.py", line 617, in read
    v = self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/alex/pumptweet/lib/python3.4/site-packages/requests/adapters.py", line 423, in send
    timeout=timeout
  File "/home/alex/pumptweet/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 640, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/alex/pumptweet/lib/python3.4/site-packages/requests/packages/urllib3/util/retry.py", line 261, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/alex/pumptweet/lib/python3.4/site-packages/requests/packages/urllib3/packages/six.py", line 686, in reraise
    raise value
  File "/home/alex/pumptweet/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 595, in urlopen
    chunked=chunked)
  File "/home/alex/pumptweet/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 395, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/home/alex/pumptweet/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 315, in _raise_timeout
    raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
requests.packages.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='pump.strugee.net', port=443): Read timed out. (read timeout=30)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./pt.py", line 21, in <module>
    pumptweet.pull_and_push(halt_on_error=halt_on_error)
  File "/home/alex/pumptweet/pumptweet/PumpTweet.py", line 203, in pull_and_push
    self.update_recent()
  File "/home/alex/pumptweet/pumptweet/PumpTweet.py", line 179, in update_recent
    activity = self.pump_me.outbox.major[0]
  File "/home/alex/pumptweet/lib/python3.4/site-packages/pypump/models/feed.py", line 391, in __getitem__
    return item[key]
  File "/home/alex/pumptweet/lib/python3.4/site-packages/pypump/models/feed.py", line 251, in __getitem__
    return item.next()
  File "/home/alex/pumptweet/lib/python3.4/site-packages/pypump/models/feed.py", line 300, in next
    return self.__next__()
  File "/home/alex/pumptweet/lib/python3.4/site-packages/pypump/models/feed.py", line 289, in __next__
    self._build_cache()
  File "/home/alex/pumptweet/lib/python3.4/site-packages/pypump/models/feed.py", line 182, in _build_cache
    for i in (self.get_cached() if self._cached else self.get_page(self.url)):
  File "/home/alex/pumptweet/lib/python3.4/site-packages/pypump/models/feed.py", line 94, in get_page
    data = self.feed._request(url, offset=self._offset, since=self._since, before=self._before)
  File "/home/alex/pumptweet/lib/python3.4/site-packages/pypump/models/feed.py", line 351, in _request
    data = self._pump.request(url, params=params)
  File "/home/alex/pumptweet/lib/python3.4/site-packages/pypump/pypump.py", line 311, in request
    **request
  File "/home/alex/pumptweet/lib/python3.4/site-packages/pypump/pypump.py", line 354, in _requester
    response = fnc(url, **kwargs)
  File "/home/alex/pumptweet/lib/python3.4/site-packages/requests/sessions.py", line 488, in get
    return self.request('GET', url, **kwargs)
  File "/home/alex/pumptweet/lib/python3.4/site-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/alex/pumptweet/lib/python3.4/site-packages/requests/sessions.py", line 596, in send
    r = adapter.send(request, **kwargs)
  File "/home/alex/pumptweet/lib/python3.4/site-packages/requests/adapters.py", line 499, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='pump.strugee.net', port=443): Read timed out. (read timeout=30)
```

Any ideas?

**Comment by strugee** [comment]
Should mention that I also sometimes see:

```
Traceback (most recent call last):
  File "/home/alex/pumptweet/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 385, in _make_request
    httplib_response = conn.getresponse(buffering=True)
TypeError: getresponse() got an unexpected keyword argument 'buffering'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/alex/pumptweet/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 387, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.4/http/client.py", line 1172, in getresponse
    response.begin()
  File "/usr/lib/python3.4/http/client.py", line 351, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.4/http/client.py", line 313, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.4/socket.py", line 371, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.4/ssl.py", line 745, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.4/ssl.py", line 617, in read
    v = self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/alex/pumptweet/lib/python3.4/site-packages/requests/adapters.py", line 403, in send
    timeout=timeout
  File "/home/alex/pumptweet/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 623, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/alex/pumptweet/lib/python3.4/site-packages/requests/packages/urllib3/util/retry.py", line 255, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/alex/pumptweet/lib/python3.4/site-packages/requests/packages/urllib3/packages/six.py", line 310, in reraise
    raise value
  File "/home/alex/pumptweet/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 578, in urlopen
    chunked=chunked)
  File "/home/alex/pumptweet/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 389, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/home/alex/pumptweet/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 314, in _raise_timeout
    raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
requests.packages.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='pump.strugee.net', port=443): Read timed out. (read timeout=30)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./pt.py", line 21, in <module>
    pumptweet.pull_and_push(halt_on_error=halt_on_error)
  File "/home/alex/pumptweet/pumptweet/PumpTweet.py", line 201, in pull_and_push
    posts = self.get_new_activities()
  File "/home/alex/pumptweet/pumptweet/PumpTweet.py", line 74, in get_new_activities
    for activity in outbox.major[:count]:
  File "/home/alex/pumptweet/lib/python3.4/site-packages/pypump/models/feed.py", line 289, in __next__
    self._build_cache()
  File "/home/alex/pumptweet/lib/python3.4/site-packages/pypump/models/feed.py", line 182, in _build_cache
    for i in (self.get_cached() if self._cached else self.get_page(self.url)):
  File "/home/alex/pumptweet/lib/python3.4/site-packages/pypump/models/feed.py", line 94, in get_page
    data = self.feed._request(url, offset=self._offset, since=self._since, before=self._before)
  File "/home/alex/pumptweet/lib/python3.4/site-packages/pypump/models/feed.py", line 351, in _request
    data = self._pump.request(url, params=params)
  File "/home/alex/pumptweet/lib/python3.4/site-packages/pypump/pypump.py", line 311, in request
    **request
  File "/home/alex/pumptweet/lib/python3.4/site-packages/pypump/pypump.py", line 354, in _requester
    response = fnc(url, **kwargs)
  File "/home/alex/pumptweet/lib/python3.4/site-packages/requests/sessions.py", line 487, in get
    return self.request('GET', url, **kwargs)
  File "/home/alex/pumptweet/lib/python3.4/site-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/alex/pumptweet/lib/python3.4/site-packages/requests/sessions.py", line 585, in send
    r = adapter.send(request, **kwargs)
  File "/home/alex/pumptweet/lib/python3.4/site-packages/requests/adapters.py", line 479, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='pump.strugee.net', port=443): Read timed out. (read timeout=30)
```

**Comment by dper** [comment]
I don't know. FWIW here are some speculations...

Are you always getting the exception in cron, and never on the command line? If so, I would guess that somehow your environments are different (different virtualenv or different version of python).  Otherwise, we should be seeing the same behavior in both of them.

When I searched for the first exception above, I found something slightly related [here](https://github.com/kennethreitz/requests/issues/1915), which suggests that the order of the exceptions is misleading, and that the final one is the underlying issue.  If that is correct, then the `ReadTimeout` is what's happening. That would suggest a network connectivity issue of some sort, perhaps.

Also, I'm using Python 3.5.2.  If there's a bug that's 3.4-specific, I won't be able to replicate it.  For reference, what version of PumpTweet are you running?

**Comment by strugee** [comment]
OK, just reproduced this on the CLI with `./pt.sh > /dev/null` (exactly what's in my crontab, minus the `cd`).

The pump server is running on the same host as pumptweet, so I doubt it's a network issue...

**Comment by strugee** [comment]
It doesn't appear on the CLI very often. FWIW I'm running pumptweet@c22279a57f44352960ef3227087313fae3b7a17e.

**Comment by dper** [comment]
Has anyone else run into this bug? Let us know if you ever do.

The PumpTweet code in that area is very simple and hasn't changed in a long time. Perhaps there's something happening in PyPump? However, we don't have much information and it's not clear how to gather more... :-(

Out of curiosity, how often does your cronjob run?

**Comment by strugee** [comment]
@dper every five minutes.

**Comment by strugee** [comment]
Worth noting that I'm running the utml-to-jade branch of pump.

**Comment by strugee** [comment]
@dper just saw this again - turns out this was an early symptom of disk problems. The server would query the db and the connection would time out before a response came back.

Shall we close? Seems like a problem we can't do much about.

**Comment by dper** [comment]
OK!

**Comment by zhangysh1995** [comment]
I had the same problem when ````pip3 install paramiko````  under Ubuntu 14.04 command-line . The errors are [here](http://paste.ubuntu.com/25189231/). After I tried several times later the package is successfully installed. It seems this problem is network-related.

My machine:
Ubuntu 14.04 official docker image
python 3.4.3
pip3

**Comment by strugee** [comment]
@zhangysh1995 you're running into a genetic problem that's completely unrelated to this project. Check your network connection.

**Comment by karan1210** [comment]
@strugee I faced same error.but  after some try I am able to install.so please go to network settings in your PC or restore your network. This error is definitely rise because of low downloading speed of internet.
