### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'replace'

### ISSUE THREAD

**Issue by strugee** [dper/pumptweet#40]
```
% ./pt.sh
Reading the config file...
Logging into the Pump server...
Logging into Twitter...
Looking at Pump outbox activity...
> note (2017-07-16 09:31:39+00:00)
> note (2017-07-16 09:05:28+00:00)
> note (2017-07-16 09:03:36+00:00)
> note (2017-07-14 22:22:34+00:00)
> image (2017-07-14 19:40:05+00:00)
> note (2017-07-14 19:38:44+00:00)
New tweet count: 3.
---------------------------------

> for all Twitter did for #NetNeutrality on the day of action, I sure still see Comcast ads on my timeline lying... https://pump.strugee.net/alex/note/ki6CrIJDTXuty2my30KD-Q
---------------------------------

> Dumb Flash keeps hanging my kernel.... https://pump.strugee.net/alex/note/9LL5vmkoT9qUxOmNK11TaA
Traceback (most recent call last):
  File "./pt.py", line 21, in <module>
    pumptweet.pull_and_push(halt_on_error=halt_on_error)
  File "/home/alex/pumptweet/pumptweet/PumpTweet.py", line 202, in pull_and_push
    self.post_all(posts)
  File "/home/alex/pumptweet/pumptweet/PumpTweet.py", line 174, in post_all
    self.post_image(post)
  File "/home/alex/pumptweet/pumptweet/PumpTweet.py", line 147, in post_image
    text = self.make_text(post)
  File "/home/alex/pumptweet/pumptweet/PumpTweet.py", line 101, in make_text
    content = strip_tags(content)
  File "/home/alex/pumptweet/pumptweet/MLStripper.py", line 51, in strip_tags
    text = replace_entities(text)
  File "/home/alex/pumptweet/pumptweet/MLStripper.py", line 45, in replace_entities
    html = html.replace(entity, char)
AttributeError: 'NoneType' object has no attribute 'replace'

% git rev-parse HEAD
3642fa254c527463ac5e0c1bfbf7a8dc2cdbbf7a
```

I reinstalled since you switched to Python 3, etc., and it just seemed cleaner. So this has the very latest PyPump 0.7 and python-twitter 3.3.

AFAICT https://pump.strugee.net/alex/image/tjIrdCZlSn2UxsVzEMvZuw is what's causing this. Perhaps because it's a profile picture change and not a regular image? I dunno. (Are those even different at the protocol layer? I really should know this, but don't.)

**Comment by dper** [comment]
@strugee Sadly, I haven't been using Pump since Microca.st went down. I dunno what is useful for you. You're welcome to file bugs here, but I can't provide any substantive assistance. Sorry!
